### PR TITLE
Translation improvement

### PR DESCRIPTION
**Pull request by ltagliamonte**
Fix few FE string translations

### CODE REVIEW

**Comment by ltagliamonte** [comment]
@eko do you mind taking a look please?

**Review by eko — APPROVED** [review]

**Comment by eko** [comment]
Thank you @ltagliamonte

**Comment by ltagliamonte** [comment]
@eko thanks for the review, what's the workflow to merge and cut a new release?

**Review by eko — APPROVED** [review]

**Review by eko — APPROVED** [review]
Hi, Thank you again. I am off actually but I will create a new release containing these changes on next monday

**Pull request merged**
